"""
    Arbeitsagentur Ausbildungssuche API

    Eine der größten Ausbildungsdatenbanken Deutschlands durchsuchen.   Die Authentifizierung funktioniert über die clientId der Ausbildungssuchesuche, die einem GET-request an         https://web.arbeitsagentur.de/weiterbildungssuche/suche entnommen werden kann:  **clientId:** infosysbub-absuche  Bei folgenden GET-requests ist die clientId als Header-Parameter 'X-API-Key' zu übergeben.   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.ausbildungssuche.model.response_aggregations import (
    ResponseAggregations,
)
from deutschland.ausbildungssuche.model.response_embedded import ResponseEmbedded
from deutschland.ausbildungssuche.model.response_links import ResponseLinks
from deutschland.ausbildungssuche.model.response_page import ResponsePage

from deutschland import ausbildungssuche

globals()["ResponseAggregations"] = ResponseAggregations
globals()["ResponseEmbedded"] = ResponseEmbedded
globals()["ResponseLinks"] = ResponseLinks
globals()["ResponsePage"] = ResponsePage
from deutschland.ausbildungssuche.model.response import Response


class TestResponse(unittest.TestCase):
    """Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponse(self):
        """Test Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
