"""
    Arbeitsagentur Ausbildungssuche API

    Eine der größten Ausbildungsdatenbanken Deutschlands durchsuchen.   Die Authentifizierung funktioniert per OAuth 2 Client Credentials mit JWTs. Folgende Client-Credentials können dafür verwendet werden:  **ClientID:** 1c852184-1944-4a9e-a093-5cc078981294  **ClientSecret:** 777f9915-9f0d-4982-9c33-07b5810a3e79.   **Achtung**: der generierte Token muss bei folgenden GET-requests im header als *'OAuthAccessToken'* inkludiert werden. Alternativ kann man bei folgenden GET-requests auch direkt die *client_id* als Header-Parameter *'X-API-Key'* übergeben - *'OAuthAccessToken'* ist in diesem Fall nicht erforderlich. 🚀   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.ausbildungssuche.model.response_aggregations_beginntermin0 import (
    ResponseAggregationsBEGINNTERMIN0,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin1 import (
    ResponseAggregationsBEGINNTERMIN1,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin2 import (
    ResponseAggregationsBEGINNTERMIN2,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin101 import (
    ResponseAggregationsBEGINNTERMIN101,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin102 import (
    ResponseAggregationsBEGINNTERMIN102,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin103 import (
    ResponseAggregationsBEGINNTERMIN103,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin104 import (
    ResponseAggregationsBEGINNTERMIN104,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin105 import (
    ResponseAggregationsBEGINNTERMIN105,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin106 import (
    ResponseAggregationsBEGINNTERMIN106,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin107 import (
    ResponseAggregationsBEGINNTERMIN107,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin108 import (
    ResponseAggregationsBEGINNTERMIN108,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin109 import (
    ResponseAggregationsBEGINNTERMIN109,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin110 import (
    ResponseAggregationsBEGINNTERMIN110,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin111 import (
    ResponseAggregationsBEGINNTERMIN111,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin112 import (
    ResponseAggregationsBEGINNTERMIN112,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin113 import (
    ResponseAggregationsBEGINNTERMIN113,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin201 import (
    ResponseAggregationsBEGINNTERMIN201,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin202 import (
    ResponseAggregationsBEGINNTERMIN202,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin203 import (
    ResponseAggregationsBEGINNTERMIN203,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin204 import (
    ResponseAggregationsBEGINNTERMIN204,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin205 import (
    ResponseAggregationsBEGINNTERMIN205,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin206 import (
    ResponseAggregationsBEGINNTERMIN206,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin207 import (
    ResponseAggregationsBEGINNTERMIN207,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin208 import (
    ResponseAggregationsBEGINNTERMIN208,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin209 import (
    ResponseAggregationsBEGINNTERMIN209,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin210 import (
    ResponseAggregationsBEGINNTERMIN210,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin211 import (
    ResponseAggregationsBEGINNTERMIN211,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin212 import (
    ResponseAggregationsBEGINNTERMIN212,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin301 import (
    ResponseAggregationsBEGINNTERMIN301,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin302 import (
    ResponseAggregationsBEGINNTERMIN302,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin303 import (
    ResponseAggregationsBEGINNTERMIN303,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin304 import (
    ResponseAggregationsBEGINNTERMIN304,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin305 import (
    ResponseAggregationsBEGINNTERMIN305,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin306 import (
    ResponseAggregationsBEGINNTERMIN306,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin307 import (
    ResponseAggregationsBEGINNTERMIN307,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin308 import (
    ResponseAggregationsBEGINNTERMIN308,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin309 import (
    ResponseAggregationsBEGINNTERMIN309,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin310 import (
    ResponseAggregationsBEGINNTERMIN310,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin311 import (
    ResponseAggregationsBEGINNTERMIN311,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin312 import (
    ResponseAggregationsBEGINNTERMIN312,
)

from deutschland import ausbildungssuche

globals()["ResponseAggregationsBEGINNTERMIN0"] = ResponseAggregationsBEGINNTERMIN0
globals()["ResponseAggregationsBEGINNTERMIN1"] = ResponseAggregationsBEGINNTERMIN1
globals()["ResponseAggregationsBEGINNTERMIN101"] = ResponseAggregationsBEGINNTERMIN101
globals()["ResponseAggregationsBEGINNTERMIN102"] = ResponseAggregationsBEGINNTERMIN102
globals()["ResponseAggregationsBEGINNTERMIN103"] = ResponseAggregationsBEGINNTERMIN103
globals()["ResponseAggregationsBEGINNTERMIN104"] = ResponseAggregationsBEGINNTERMIN104
globals()["ResponseAggregationsBEGINNTERMIN105"] = ResponseAggregationsBEGINNTERMIN105
globals()["ResponseAggregationsBEGINNTERMIN106"] = ResponseAggregationsBEGINNTERMIN106
globals()["ResponseAggregationsBEGINNTERMIN107"] = ResponseAggregationsBEGINNTERMIN107
globals()["ResponseAggregationsBEGINNTERMIN108"] = ResponseAggregationsBEGINNTERMIN108
globals()["ResponseAggregationsBEGINNTERMIN109"] = ResponseAggregationsBEGINNTERMIN109
globals()["ResponseAggregationsBEGINNTERMIN110"] = ResponseAggregationsBEGINNTERMIN110
globals()["ResponseAggregationsBEGINNTERMIN111"] = ResponseAggregationsBEGINNTERMIN111
globals()["ResponseAggregationsBEGINNTERMIN112"] = ResponseAggregationsBEGINNTERMIN112
globals()["ResponseAggregationsBEGINNTERMIN113"] = ResponseAggregationsBEGINNTERMIN113
globals()["ResponseAggregationsBEGINNTERMIN2"] = ResponseAggregationsBEGINNTERMIN2
globals()["ResponseAggregationsBEGINNTERMIN201"] = ResponseAggregationsBEGINNTERMIN201
globals()["ResponseAggregationsBEGINNTERMIN202"] = ResponseAggregationsBEGINNTERMIN202
globals()["ResponseAggregationsBEGINNTERMIN203"] = ResponseAggregationsBEGINNTERMIN203
globals()["ResponseAggregationsBEGINNTERMIN204"] = ResponseAggregationsBEGINNTERMIN204
globals()["ResponseAggregationsBEGINNTERMIN205"] = ResponseAggregationsBEGINNTERMIN205
globals()["ResponseAggregationsBEGINNTERMIN206"] = ResponseAggregationsBEGINNTERMIN206
globals()["ResponseAggregationsBEGINNTERMIN207"] = ResponseAggregationsBEGINNTERMIN207
globals()["ResponseAggregationsBEGINNTERMIN208"] = ResponseAggregationsBEGINNTERMIN208
globals()["ResponseAggregationsBEGINNTERMIN209"] = ResponseAggregationsBEGINNTERMIN209
globals()["ResponseAggregationsBEGINNTERMIN210"] = ResponseAggregationsBEGINNTERMIN210
globals()["ResponseAggregationsBEGINNTERMIN211"] = ResponseAggregationsBEGINNTERMIN211
globals()["ResponseAggregationsBEGINNTERMIN212"] = ResponseAggregationsBEGINNTERMIN212
globals()["ResponseAggregationsBEGINNTERMIN301"] = ResponseAggregationsBEGINNTERMIN301
globals()["ResponseAggregationsBEGINNTERMIN302"] = ResponseAggregationsBEGINNTERMIN302
globals()["ResponseAggregationsBEGINNTERMIN303"] = ResponseAggregationsBEGINNTERMIN303
globals()["ResponseAggregationsBEGINNTERMIN304"] = ResponseAggregationsBEGINNTERMIN304
globals()["ResponseAggregationsBEGINNTERMIN305"] = ResponseAggregationsBEGINNTERMIN305
globals()["ResponseAggregationsBEGINNTERMIN306"] = ResponseAggregationsBEGINNTERMIN306
globals()["ResponseAggregationsBEGINNTERMIN307"] = ResponseAggregationsBEGINNTERMIN307
globals()["ResponseAggregationsBEGINNTERMIN308"] = ResponseAggregationsBEGINNTERMIN308
globals()["ResponseAggregationsBEGINNTERMIN309"] = ResponseAggregationsBEGINNTERMIN309
globals()["ResponseAggregationsBEGINNTERMIN310"] = ResponseAggregationsBEGINNTERMIN310
globals()["ResponseAggregationsBEGINNTERMIN311"] = ResponseAggregationsBEGINNTERMIN311
globals()["ResponseAggregationsBEGINNTERMIN312"] = ResponseAggregationsBEGINNTERMIN312
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin import (
    ResponseAggregationsBEGINNTERMIN,
)


class TestResponseAggregationsBEGINNTERMIN(unittest.TestCase):
    """ResponseAggregationsBEGINNTERMIN unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseAggregationsBEGINNTERMIN(self):
        """Test ResponseAggregationsBEGINNTERMIN"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseAggregationsBEGINNTERMIN()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
