"""
    Arbeitsagentur Ausbildungssuche API

    Eine der größten Ausbildungsdatenbanken Deutschlands durchsuchen.   Die Authentifizierung funktioniert über die clientId der Ausbildungssuchesuche, die einem GET-request an         https://web.arbeitsagentur.de/weiterbildungssuche/suche entnommen werden kann:  **clientId:** infosysbub-absuche  Bei folgenden GET-requests ist die clientId als Header-Parameter 'X-API-Key' zu übergeben.   # noqa: E501

    The version of the OpenAPI document: 1.0.1
    Contact: andreasfischer1985@web.de
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.ausbildungssuche.model.response_aggregations_anbieter import (
    ResponseAggregationsANBIETER,
)
from deutschland.ausbildungssuche.model.response_aggregations_anzahlausgefiltert import (
    ResponseAggregationsANZAHLAUSGEFILTERT,
)
from deutschland.ausbildungssuche.model.response_aggregations_anzahlgesamt import (
    ResponseAggregationsANZAHLGESAMT,
)
from deutschland.ausbildungssuche.model.response_aggregations_beginntermin import (
    ResponseAggregationsBEGINNTERMIN,
)
from deutschland.ausbildungssuche.model.response_aggregations_bildungsarten import (
    ResponseAggregationsBILDUNGSARTEN,
)
from deutschland.ausbildungssuche.model.response_aggregations_integrationstypen import (
    ResponseAggregationsINTEGRATIONSTYPEN,
)
from deutschland.ausbildungssuche.model.response_aggregations_regionen import (
    ResponseAggregationsREGIONEN,
)
from deutschland.ausbildungssuche.model.response_aggregations_schulabschluesse import (
    ResponseAggregationsSCHULABSCHLUESSE,
)
from deutschland.ausbildungssuche.model.response_aggregations_unterrichtsformen import (
    ResponseAggregationsUNTERRICHTSFORMEN,
)
from deutschland.ausbildungssuche.model.response_aggregations_vorbereitendehilfentypen import (
    ResponseAggregationsVORBEREITENDEHILFENTYPEN,
)

from deutschland import ausbildungssuche

globals()["ResponseAggregationsANBIETER"] = ResponseAggregationsANBIETER
globals()[
    "ResponseAggregationsANZAHLAUSGEFILTERT"
] = ResponseAggregationsANZAHLAUSGEFILTERT
globals()["ResponseAggregationsANZAHLGESAMT"] = ResponseAggregationsANZAHLGESAMT
globals()["ResponseAggregationsBEGINNTERMIN"] = ResponseAggregationsBEGINNTERMIN
globals()["ResponseAggregationsBILDUNGSARTEN"] = ResponseAggregationsBILDUNGSARTEN
globals()[
    "ResponseAggregationsINTEGRATIONSTYPEN"
] = ResponseAggregationsINTEGRATIONSTYPEN
globals()["ResponseAggregationsREGIONEN"] = ResponseAggregationsREGIONEN
globals()["ResponseAggregationsSCHULABSCHLUESSE"] = ResponseAggregationsSCHULABSCHLUESSE
globals()[
    "ResponseAggregationsUNTERRICHTSFORMEN"
] = ResponseAggregationsUNTERRICHTSFORMEN
globals()[
    "ResponseAggregationsVORBEREITENDEHILFENTYPEN"
] = ResponseAggregationsVORBEREITENDEHILFENTYPEN
from deutschland.ausbildungssuche.model.response_aggregations import (
    ResponseAggregations,
)


class TestResponseAggregations(unittest.TestCase):
    """ResponseAggregations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseAggregations(self):
        """Test ResponseAggregations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResponseAggregations()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
